#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Jul 21 12:31:15 2018

@author: tylermeyers
"""

import pandas as pd
import numpy as np
import pyodbc
import openpyxl
from datetime import datetime
from openpyxl.utils import coordinate_from_string, column_index_from_string

#-----------------------------------------------------------------------------------------------------
#This program is used to pull data from SNL by transforming the data into a more useable format
#User will input start and end dates, company and the indicators for the fields
#-----------------------------------------------------------------------------------------------------

beg_date = input("Enter the end of month date for first month\n"+
                     "that you want to pull from SNL:    ")

end_date = input("Enter the end of month date for last month\n"+
                     "that you want to pull from SNL:    ")
comp_list = input("Enter the codes of the companies you\n"
                  "you want to include eg: KEY, MSFT, GOOG:  ")
field_list = input("Enter the Field names from the master list\n"
                   "eg: GROSS_LOANS_&_LEASES   ")
destfol = input("Enter the filepath where you would like the \n"
                "Report saved:     ")

def comp_converter(comp_list):
    comp_list = comp_list.split(",")
    comp_list=[x.upper() for x in comp_list]
    
    return comp_list

field_list = comp_converter(field_list)

comp_list = comp_converter(comp_list)
df= pd.DataFrame(comp_list, columns =['Company'])
df['Start']=beg_date
df['End']=end_date
print(df)
df2 = pd.concat([pd.DataFrame({"dt": pd.date_range(row.Start, row.End, freq='Q'), 
                'Company': row.Company}, columns=['dt','Company'])
    for i, row in df.iterrows()], ignore_index=True)

df2['Qtr'] = pd.PeriodIndex(pd.to_datetime(df2.dt), freq='Q')

for fld in field_list:
    df2[fld] = ""
    
wbName=destfol+"/SNL_PULL.xlsx"


writer = pd.ExcelWriter(wbName)
df2.to_excel(writer, "Detail",)
writer.save()

wb = openpyxl.load_workbook(wbName)

print(destfol)
ws = wb.get_sheet_by_name("Detail")

for col_cells in ws.iter_cols(min_row = 2,min_col=5):
    for cell in col_cells:
        form = '=SNLData(%s, C%s, %s1, D%s, %s)' % ('"1"', cell.coordinate[1],cell.coordinate[0], cell.coordinate[1],'"Current/Restated"' )
        cell.value=form 
        print('%s: cell.value=%s' % (cell, cell.value))
        
wb.save(wbName)

n ='SNLData("1",c%d, %s%d, D%d, "Current/Restated")'
#-----------------------------------------------------------------------------------------------------
#Iterate over columns 
#-----------------------------------------------------------------------------------------------------
x = 5
col_indices = {n for n, cell in enumerate(ws.rows[0]) if cell.value in field_list}
print(col_indices)
    for row in sheet.rows[1:]:
    for index, cell in enumerate(row):
         if index in col_indices:
             if cell.value.upper() == 'OldValue1':
                  cell.value = 1
                  print(cell.value)
             elif cell.value.upper() == 'OldValue2':
                 cell.value = 2
                 print(cell.value)




print(ws["F5"].value)

df2.drop(['fld'],axis = 1)
print(df2)
print(beg_date)
print(end_date)
print(comp_list)
print(dates.tolist())
print(field_list)

